### ISSUE TITLE
Question about libOUM

### ISSUE THREAD

**Issue by stdoo** [UWSysLab/NOPaxos#2]
Hi @nicklijl ,
I'm curious about the libOUM library which can ensure ordering by discarding messages that are received out of order. Since there's no document about the code, it's really hard for me to find the code which implements libOUM. Need some help. Thanks.

**Comment by JLin-Li** [comment]
For our current implementation, we didn't implement libOUM explicitly, instead handled drop notification, session termination, etc. implicitly in the NOPaxos replica code.

You can look at `sequencer/sequencer.cc` to see how we insert message number and session id into packets. And all message number, session id handling are done inside `nopaxos/replica.cc`, in particular `TryProcessClientRequest` function.

**Comment by stdoo** [comment]
Get it. Thanks very much.
